name: haskell-dap
version: '0.0.15.0'
synopsis: Haskell implementation of the DAP interface data.
description: Please see README.md
category: Development
author: phoityne_hs
maintainer: phoityne.hs@gmail.com
copyright: 2017-2020 phoityne_hs
license: BSD3
homepage: https://github.com/phoityne/haskell-dap
bug-reports: https://github.com/phoityne/haskell-dap/issues
extra-source-files:
- README.md
- Changelog.md

library:
  source-dirs: src
  exposed-modules:
  - Haskell.DAP
  dependencies:
  - base >=4.7 && <5
  - containers




