name: haskell-dap
version: '0.0.14.0'
synopsis: Haskell implementation of the DAP interface data.
description: Please see README.md
category: Development
author: phoityne_hs
maintainer: phoityne.hs@gmail.com
copyright: 2017-2019 phoityne_hs
license: BSD3
homepage: https://github.com/phoityne/haskell-dap
bug-reports: https://github.com/phoityne/haskell-dap/issues
extra-source-files:
- README.md
- Changelog.md
- src-c-8.0/HsVersions.h
- src-c-8.0/PosixSource.h
- src-c-8.2/HsVersions.h
- src-c-8.2/PosixSource.h
- src-c-8.4/HsVersions.h
- src-c-8.4/PosixSource.h
- src-c-8.6/HsVersions.h
- src-c-8.6/PosixSource.h

library:
  source-dirs: src
  exposed-modules:
  - Haskell.DAP
  - GHCi.DAP.IFData
  dependencies:
  - base >=4.7 && <5
  - containers

executables:
  haskell-dap:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-unused-do-bind
    - -fno-warn-name-shadowing
    cc-options: -fPIC
    cpp-options: -DGHCI
    dependencies:
    - base >=4.7 && <5
    - ghc
    - ghci
    - ghc-paths
    - transformers
    - containers
    - time
    - directory
    - haskeline
    - array
    - process
    - ghc-boot
    - filepath
    - bytestring
    - deepseq
    - haskell-dap
    - text
    when:
    - condition: (impl(ghc >=8.0.0)) && (impl(ghc <8.1.0))
      source-dirs: app-ghc-8.0
    - condition: (impl(ghc >=8.2.0)) && (impl(ghc <8.3.0))
      source-dirs: app-ghc-8.2
    - condition: (impl(ghc >=8.4.0)) && (impl(ghc <8.5.0))
      source-dirs: app-ghc-8.4
    - condition: (impl(ghc >=8.6.0)) && (impl(ghc <8.7.0))
      source-dirs: app-ghc-8.6

    - condition: (impl(ghc >=8.0.0)) && (impl(ghc <8.1.0))
      c-sources: src-c-8.0/hschooks.c
      include-dirs:
      - src-c-8.0/
    - condition: (impl(ghc >=8.2.0)) && (impl(ghc <8.3.0))
      c-sources: src-c-8.2/hschooks.c
      include-dirs:
      - src-c-8.2/
    - condition: (impl(ghc >=8.4.0)) && (impl(ghc <8.5.0))
      c-sources: src-c-8.4/hschooks.c
      include-dirs:
      - src-c-8.4/
    - condition: (impl(ghc >=8.6.0)) && (impl(ghc <8.7.0))
      c-sources: src-c-8.6/hschooks.c
      include-dirs:
      - src-c-8.6/
    - condition: os(windows)
      then:
        dependencies:
        - Win32
      else:
        dependencies:
        - unix
